### ISSUE TITLE
cffi-1.3.0-cp26-none-linux_x86_64.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by svh1985** [plesk/letsencrypt-plesk#68]
Hi there,

I have Plesk 12.5.30 Update #19 on CentOS 6.6 (Final) and I installed the Let's Encrypt Plugin.

But whenever I request a certificate with or without the WWW subdomain, I receive the following error:
`Error: Let's Encrypt SSL certificate installation failed: Failed letsencrypt execution: /usr/local/psa/admin/plib/modules/letsencrypt/scripts/le-run: line 13: /usr/local/psa/var/modules/letsencrypt//venv/bin/letsencrypt: No such file or directory `

Is there anyone who encountered this problem and manage to solve it or know the solution for this problem?

Thanks!

Regards,

Stephan

**Comment by xgin** [comment]
That means the installation of the extension has been failed.
Try to reinstall it and report the reason of the failure.

**Comment by svh1985** [comment]
Hi xgin,

I've reinstalled and got this error:
`Error: Failed to install the extension: Executing /usr/local/psa/admin/plib/modules/letsencrypt/scripts/post-install.php failed: Bootstrapping dependencies for centos 6 x86_64... Creating virtual environment... Updating letsencrypt and virtual environment dependencies... You are using pip version 6.1.1, however version 8.0.2 is available. You should consider upgrading via the 'pip install --upgrade pip' command. You are using pip version 6.1.1, however version 8.0.2 is available. You should consider upgrading via the 'pip install --upgrade pip' command. cffi-1.3.0-cp26-none-linux_x86_64.whl is not a supported wheel on this platform. `

After that, I uninstalled the plugin, executed the command pip install --upgrade pip, that succesfully installed pip 8.0.2. Then I installed the Lets Encrypt Plugin again but still got the same error.

**Comment by xgin** [comment]
Could you show the version of your python running `python -V`

**Comment by svh1985** [comment]
Says Python 2.6.6.
But Python 2.7 is also installed in /usr/local/bin/python2.7

**Comment by neolinux** [comment]
I have the same Problem... any solution?

**Comment by dominic-ks** [comment]
I am currently struggling with the same error messages when attempting to install the Plesk Extension: 

`Error: Failed to install the extension: Executing /usr/local/psa/admin/plib/modules/letsencrypt/scripts/post-install.php failed: Bootstrapping dependencies for centos 6 x86_64... Creating virtual environment... Updating letsencrypt and virtual environment dependencies... cffi-1.3.0-cp26-none-linux_x86_64.whl is not a supported wheel on this platform.`

I am also in a similar situation with regards to Python, python -V gives 2.6.6 and I have installed Python2.7 in /usr/local/bin/python2.7 as the general advice seems to be not not update the core 2.6.x as essential services like yum rely on it. 

That said, I've also come to understand that the cp26 part of the cffi file name is referring to 2.6.x and so I'm not completely sure that the python version is the issue here.

**Comment by svh1985** [comment]
I eventually gave up and decided to get a new VPS with ‪Ubuntu 14.04.3 LTS‬. I did a Plesk backup/restore and everything works like a charm now. CentOS 6.6 (Final) gave me to much headache.

**Comment by dominic-ks** [comment]
Well I certainly hope I can avoid a server migration if I can help it. This is the only issue I've had in 18 months.

**Comment by muelli75** [comment]
Have an similar issue here on ‪Debian 7.9‬, Plesk version: 12.5.30 Update #28

If I try to install Lets Encrypt 1.5 the following error appears:

Error: Failed to install the extension: Executing /opt/psa/admin/plib/modules/letsencrypt/scripts/post-install.php failed: Bootstrapping dependencies for debian wheezy... Selecting previously unselected package plesk-letsencrypt-pre. (Reading database ... 198803 files and directories currently installed.) Unpacking plesk-letsencrypt-pre (from .../plesk-letsencrypt-pre_1.0.0-debian7.0.16032214_amd64.deb) ... Setting up plesk-letsencrypt-pre (1.0.0-debian7.0.16032214) ... Creating virtual environment... The --no-site-packages flag is deprecated; it is now the default behavior. Updating letsencrypt and virtual environment dependencies... Could not find .egg-info directory in install record for setuptools from https://pypi.python.org/packag... in /opt/psa/var/modules/letsencrypt/venv.a0vZC/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg Could not find .egg-info directory in install record for pip from https://pypi.python.org/packag... in /opt/psa/var/modules/letsencrypt/venv.a0vZC/lib/python2.7/site-packages/pip-1.1-py2.7.egg cffi-1.5.2-cp26-cp26mu-linux_x86_64.whl is not a supported wheel on this platform.

Any help out there?

**Comment by dominic-ks** [comment]
Just to share, not sure how helpful this will be, but the server I was using was a VPS with 123-reg.co.uk  and ice since switched to a new provider, very similar set up, still on CentOS 6.7 and it's worked perfectly since. Unfortunately the reason I moved was because the host manage to wipe my server so I'm not sure what the difference is.

**Comment by xgin** [comment]
We have released a new version 1.6 of the extension.
Major change is a switch from system python to plesk-py27 on all unix OSes.
Distribution of own python should increase installation reliability and resolve the issue.
Please, check your installation with the latest update.
Feel free to reopen the issue if the problem is still reproduced.

**Comment by Committing** [comment]
This problem still happens for me on centos 6.7.

https://gyazo.com/120b403aa383a6fad5ba55b4ab02023e

I am on 123-reg as well. @dominic-ks They deleted my VPS as well.

**Comment by xgin** [comment]
@Committing try this: https://kb.plesk.com/en/113175

**Comment by dominic-ks** [comment]
@Committing Are you still with 123-reg? If you still have one of their VPS packages my best suggestion is to leave them behind and move elsewhere. The reduction in the amount of troubleshooting and issues like these I've had to deal with since moving elsewhere has been amazing. Like I said I don't have their server any more to reference, but I can only assume the images that they use for auto-provisioning VPS platforms are outdated with little to no attention paid to them, and this must be where at least some of these issues have been coming from.

**Comment by Committing** [comment]
Thanks @xgin I'll give that a try when I'm home from work later this evening.

@dominic-ks - Unfortunately I am still with them. Right after the issue occurred they charged my account for another year so I thought I might as well carry on. The deleted around 80 sites that I ran. I've only recovered 40 or so. It took them over a month to finally give me backups of the data.

I've been thinking of moving to Digital Ocean and just manage everything through cli on Centos. All  these management softwares like webmin/plesk/cpanel just get in the way really. Out of interest, who did you move to as a replacement from 123reg? Cheers

**Comment by dominic-ks** [comment]
@Committing I moved to a local independent provider of IT services - https://aff-it.co.uk - they don't actually specifically advertise VPS services but they will cook you one up to order. More expensive for sure, but the service I've received has made 123-reg look like a bunch of school kids who didn't know what they were getting themselves into. Would highly recommend, the peace of mind for my customer's websites and businesses is worth it. 

You shouldn't settle for 123-reg just charging you another year, I thought they offered everyone affected 6 months > 1 year free + a premium backup service?

When I left I got a refund from them and charged them a load of business costs I'd incurred in the meantime.

Potentially not the place for this discussion, ping me directly if you want to chat more.
